### ISSUE TITLE
lines 11 - 14 these should live inside your ".env" file. Review module 40.5 for more details

### ISSUE THREAD

**Issue by thefonso** [ChrisDowdDeveloper/RestaurantReservation#1]
https://github.com/ChrisDowdDeveloper/RestaurantReservation/blob/05761a8dd02cc73691ba53349ce134948cf176d9/back-end/knexfile.js#L11

**Comment by ChrisDowdDeveloper** [comment]
Those lines do live inside in my .env folder, but I did notice this,

inside the test folder in the front-end folder on my code, the test only
checks that the title is rendered. Also in the front-end folder there is
another folder called "e2e". That folder contains many tests that look like
they take screenshots of the code when it passes the tests. Screenshots of
what I am referring to will be sent over slack
