### ISSUE TITLE
Why is the Async keyword here

### ISSUE THREAD

**Issue by thefonso** [ChrisDowdDeveloper/RestaurantReservation#3]
https://github.com/ChrisDowdDeveloper/RestaurantReservation/blob/930d7ee1607e3563811f70a6ea3296c21e83c76e/back-end/src/reservations/reservations.service.js#L33

**Comment by ChrisDowdDeveloper** [comment]
The lines that you said are supposed to be in my .env file are currently in
my .env file. Is there something that I am missing? Am I supposed to put it
in the .env.sample?

 I saw that I forgot to do the heroku config when deploying but other than
that I am having trouble understanding
